server:
  port: 8080

spring:
  application:
    name: edusync-gateway
  codec:
    max-in-memory-size: 50MB
  cloud:
    gateway:
      httpclient:
        connect-timeout: 60000
        response-timeout: 60s
      routes:
        - id: auth-service
          uri: lb://EDUSYNC-AUTH
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: finance-service
          uri: lb://EDUSYNC-FINANCE
          predicates:
            - Path=/api/finance/**
          filters:
            - StripPrefix=1
        - id: hr-service
          uri: lb://EDUSYNC-HR
          predicates:
            - Path=/api/hr/**
          filters:
            - StripPrefix=1
        - id: student-service
          uri: lb://EDUSYNC-STUDENT
          predicates:
            - Path=/api/student/**
          filters:
            - StripPrefix=1
        - id: sales-service
          uri: lb://EDUSYNC-SALES
          predicates:
            - Path=/api/sales/**
          filters:
            - StripPrefix=1
        - id: academics-service
          uri: lb://EDUSYNC-ACADEMICS
          predicates:
            - Path=/api/academics/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
