server:
  port: 8084

spring:
  application:
    name: edusync-sales
  datasource:
    url: jdbc:postgresql://localhost:5432/edusync_erp
    username: edusync
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Service URLs for inter-service communication
student:
  service:
    url: http://localhost:8083

finance:
  service:
    url: http://localhost:8081

---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres:5432/edusync_erp

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/

# Service URLs for inter-service communication (Docker)
student:
  service:
    url: http://edusync-student:8083

finance:
  service:
    url: http://edusync-finance:8081
